apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arangodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arangodb.labels" . | nindent 4 }}
data:
  ARANGO_NO_AUTH: "1"
  VIRTUAL_HOST: arango-db
  VIRTUAL_PORT: "8520"
  ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: 8G
