apiVersion: v1
kind: PersistentVolume
metadata:
  name: arango-pv-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s-data/arangodb/"
