apiVersion: v1
kind: Service
metadata:
  name: {{ include "arangodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arangodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "arangodb.selectorLabels" . | nindent 4 }}
